import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Nav from "./nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const date = new Date();
const month = date.getMonth() + 1;
const year = date.getFullYear();
const day = date.getDate();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Nav />
        <main className="main">
          {children}
          <Toaster />
        </main>
        <footer className="flex items-center justify-center p-4 border-t border-solid border-black">
          <p>
            {year}년 {month}월 {day}일 이희재
          </p>
        </footer>
      </body>
    </html>
  );
}
