import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <nav className="flex items-center gap-4 p-4 border-b border-solid border-black font-semibold">
            <Link href="/">
              <Image
                src="/logo.png"
                alt="logo"
                width={50}
                height={50}
                priority
              />
            </Link>
            <Link href="/write">NEW</Link>
            <Link href="/login" className="ml-auto">
              LOGIN
            </Link>
          </nav>
        </header>
        <main className="main">
          {children}
          <Toaster />
        </main>
        <footer className="flex items-center justify-center p-4 border-t border-solid border-black">
          <p>2024년 10월 22일 이희재</p>
        </footer>
      </body>
    </html>
  );
}
